### ISSUE TITLE
Suggest repo rename

### ISSUE THREAD

**Issue by sindrenm** [hyperoslo/memory-orm#2]
Considering this repo contains the actual library, I think we should at least ditch the “Demo” part of the repo name. I also suggest we kebab-case it, so it becomes **memory-orm** instead. It's (relatively) consistent with most other repos we've got. :smile:

**Comment by sindrenm** [comment]
I've renamed the repo to use [kebab-case], keeping the “demo” part for now.

[kebab-case]: http://c2.com/cgi/wiki?KebabCase

**Comment by jeantuffier** [comment]
yes actually we should rename it as you said. Does not really make sense to keep the "demo" part

**Comment by sindrenm** [comment]
Done. :+1:
